### ISSUE TITLE
Ordering of emails in gallery

### ISSUE THREAD

**Issue by thegengen** [remoteoss/swoosh_gallery#11]
Hi there.

First of all, thank you for this awesome library. It's a great value add for us!

I have a question: could we have the ordering of `preview` calls inside the gallery module determine the order that is used in the UI? Having them sorted alphabetically is a bit arbitrary.

I'd be happy to submit a PR for this, just wanted to gauge your interest.

Thanks for your work!

**Comment by vrcca** [comment]
That would be really useful! PRs are welcome! 💜

**Comment by vrcca** [comment]
Thank you @sechosebio and @thegengen for the contribution!! Sorry for the huge delay 🙈
